"""initial foundation

Revision ID: 506a9dad4b92
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "506a9dad4b92"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum(
                "GENERAL_CSC_RESEARCH",
                "UNIVERSITY_DISCOVERY",
                "UNIVERSITY_RESEARCH",
                "PROGRAM_RESEARCH",
                "PROFESSOR_DISCOVERY",
                "PROFESSOR_RESEARCH",
                "PROFESSOR_PUBLICATION_RESEARCH",
                "STUDY_PLAN_GENERATION",
                "EMAIL_DRAFT",
                "EMAIL_SEND",
                "INBOX_SYNC",
                name="research_jobs_job_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "RUNNING",
                "WAITING_FOR_REVIEW",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="research_jobs_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "UNIVERSITY",
                "PROGRAM",
                "PROFESSOR",
                "PROFESSOR_CONTACT",
                "SOURCE",
                "PUBLICATION",
                "STUDY_PLAN",
                "EMAIL_RECORD",
                "CONTACT_ATTEMPT",
                name="research_jobs_entity_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(entity_id IS NULL) = (entity_type IS NULL)", name=op.f("ck_research_jobs_target_pair")
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND revision >= 0", name=op.f("ck_research_jobs_counters_nonnegative")
        ),
        sa.CheckConstraint(
            "priority >= 0 AND priority <= 100", name=op.f("ck_research_jobs_priority_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_jobs")),
    )
    with op.batch_alter_table("research_jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_research_jobs_queue", ["status", "priority", "created_at"], unique=False
        )

    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "OFFICIAL_UNIVERSITY",
                "OFFICIAL_GOVERNMENT",
                "OFFICIAL_FACULTY",
                "OFFICIAL_LAB",
                "PUBLICATION",
                "ACADEMIC_INDEX",
                "SECONDARY",
                "OTHER",
                name="sources_source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column("domain", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=True),
        sa.Column("local_snapshot_path", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_table(
        "universities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("chinese_name", sa.Text(), nullable=True),
        sa.Column("abbreviation", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("province", sa.Text(), nullable=True),
        sa.Column("official_website", sa.Text(), nullable=True),
        sa.Column("international_admissions_url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_universities")),
    )
    op.create_table(
        "professors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("name_en", sa.Text(), nullable=False),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("name_zh", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("official_profile_url", sa.Text(), nullable=True),
        sa.Column("research_summary", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "RESEARCHING",
                "SHORTLISTED",
                "CONTACTED",
                "ARCHIVED",
                name="professors_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("last_verified_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_professors_university_id_universities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professors")),
    )
    with op.batch_alter_table("professors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_professors_university_id"), ["university_id"], unique=False
        )

    op.create_table(
        "programs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("university_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "degree_level",
            sa.Enum(
                "MASTERS",
                "PHD",
                "BACHELORS",
                name="programs_degree_level",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("department", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("duration_years", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("tuition_cny", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("application_deadline", sa.Date(), nullable=True),
        sa.Column("csc_supported", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "duration_years IS NULL OR duration_years > 0",
            name=op.f("ck_programs_positive_duration"),
        ),
        sa.CheckConstraint(
            "tuition_cny IS NULL OR tuition_cny >= 0", name=op.f("ck_programs_nonnegative_tuition")
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_programs_university_id_universities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programs")),
    )
    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_programs_university_id"), ["university_id"], unique=False
        )

    op.create_table(
        "research_facts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum(
                "UNIVERSITY",
                "PROGRAM",
                "PROFESSOR",
                "PROFESSOR_CONTACT",
                "SOURCE",
                "PUBLICATION",
                "STUDY_PLAN",
                "EMAIL_RECORD",
                "CONTACT_ATTEMPT",
                name="research_facts_entity_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.Text(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "verification_status",
            sa.Enum(
                "VERIFIED_OFFICIAL",
                "VERIFIED_PUBLICATION",
                "VERIFIED_SECONDARY",
                "UNVERIFIED",
                "CONFLICTING",
                "OUTDATED",
                name="research_facts_verification_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_research_facts_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_facts")),
    )
    with op.batch_alter_table("research_facts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_facts_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "email_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("professor_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column("provider_thread_id", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "REVIEW_REQUIRED",
                "APPROVED",
                "SCHEDULED",
                "SENT",
                "REPLIED",
                "FOLLOW_UP_DUE",
                "CLOSED",
                "FAILED",
                name="email_records_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("received_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["professor_id"],
            ["professors.id"],
            name=op.f("fk_email_records_professor_id_professors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_records")),
    )
    with op.batch_alter_table("email_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_records_professor_id"), ["professor_id"], unique=False
        )

    op.create_table(
        "professor_contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("professor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "contact_type",
            sa.Enum(
                "EMAIL",
                "UNIVERSITY_PROFILE",
                "LAB_PAGE",
                "ORCID",
                "DBLP",
                "GOOGLE_SCHOLAR",
                "SEMANTIC_SCHOLAR",
                "RESEARCHGATE",
                "LINKEDIN",
                "PROFESSIONAL_CONTACT_FORM",
                "OTHER",
                name="professor_contacts_contact_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["professor_id"],
            ["professors.id"],
            name=op.f("fk_professor_contacts_professor_id_professors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_professor_contacts_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_professor_contacts")),
    )
    with op.batch_alter_table("professor_contacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_professor_contacts_professor_id"), ["professor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_professor_contacts_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "publications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("professor_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("venue", sa.Text(), nullable=True),
        sa.Column("doi", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["professor_id"],
            ["professors.id"],
            name=op.f("fk_publications_professor_id_professors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_publications_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
    )
    with op.batch_alter_table("publications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_publications_professor_id"), ["professor_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_publications_source_id"), ["source_id"], unique=False)

    op.create_table(
        "study_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("professor_id", sa.Uuid(), nullable=True),
        sa.Column("university_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "REVIEW_REQUIRED",
                "APPROVED",
                "ARCHIVED",
                name="study_plans_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("version > 0", name=op.f("ck_study_plans_positive_version")),
        sa.ForeignKeyConstraint(
            ["professor_id"],
            ["professors.id"],
            name=op.f("fk_study_plans_professor_id_professors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["universities.id"],
            name=op.f("fk_study_plans_university_id_universities"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_plans")),
    )
    with op.batch_alter_table("study_plans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_study_plans_professor_id"), ["professor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_study_plans_university_id"), ["university_id"], unique=False
        )

    op.create_table(
        "contact_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("professor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "EMAIL",
                "UNIVERSITY_PROFILE",
                "LAB_PAGE",
                "ORCID",
                "DBLP",
                "GOOGLE_SCHOLAR",
                "SEMANTIC_SCHOLAR",
                "RESEARCHGATE",
                "LINKEDIN",
                "PROFESSIONAL_CONTACT_FORM",
                "OTHER",
                name="contact_attempts_channel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("email_record_id", sa.Uuid(), nullable=True),
        sa.Column("attempted_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_record_id"],
            ["email_records.id"],
            name=op.f("fk_contact_attempts_email_record_id_email_records"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["professor_id"],
            ["professors.id"],
            name=op.f("fk_contact_attempts_professor_id_professors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact_attempts")),
    )
    with op.batch_alter_table("contact_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_contact_attempts_email_record_id"), ["email_record_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_contact_attempts_professor_id"), ["professor_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contact_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contact_attempts_professor_id"))
        batch_op.drop_index(batch_op.f("ix_contact_attempts_email_record_id"))

    op.drop_table("contact_attempts")
    with op.batch_alter_table("study_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_study_plans_university_id"))
        batch_op.drop_index(batch_op.f("ix_study_plans_professor_id"))

    op.drop_table("study_plans")
    with op.batch_alter_table("publications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publications_source_id"))
        batch_op.drop_index(batch_op.f("ix_publications_professor_id"))

    op.drop_table("publications")
    with op.batch_alter_table("professor_contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_professor_contacts_source_id"))
        batch_op.drop_index(batch_op.f("ix_professor_contacts_professor_id"))

    op.drop_table("professor_contacts")
    with op.batch_alter_table("email_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_records_professor_id"))

    op.drop_table("email_records")
    with op.batch_alter_table("research_facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_facts_source_id"))

    op.drop_table("research_facts")
    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_programs_university_id"))

    op.drop_table("programs")
    with op.batch_alter_table("professors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_professors_university_id"))

    op.drop_table("professors")
    op.drop_table("universities")
    op.drop_table("sources")
    with op.batch_alter_table("research_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_research_jobs_queue")

    op.drop_table("research_jobs")
    # ### end Alembic commands ###
