"""job leases and retries

Revision ID: ee8576e1a3fb
Revises: 506a9dad4b92
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ee8576e1a3fb"
down_revision: str | None = "506a9dad4b92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Phase 1 allowed manual RUNNING records without ownership metadata. Requeue
    # those before adding a constraint that requires every RUNNING row to be leased.
    op.execute(
        "UPDATE research_jobs SET status='QUEUED', started_at=NULL, "
        "revision=revision+1, "
        "error_message='Recovered legacy unleased RUNNING job' WHERE status='RUNNING'"
    )

    with op.batch_alter_table("research_jobs", schema=None, recreate="always") as batch_op:
        batch_op.add_column(sa.Column("worker_id", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("claim_token", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("lease_expires_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("next_attempt_at", sa.DateTime(), nullable=True))
        batch_op.create_check_constraint(
            batch_op.f("ck_research_jobs_running_lease"),
            "(status = 'RUNNING') = (worker_id IS NOT NULL AND claim_token IS NOT NULL "
            "AND lease_expires_at IS NOT NULL)",
        )
        batch_op.create_index(
            "ix_research_jobs_lease", ["status", "lease_expires_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("research_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_research_jobs_lease")
        batch_op.drop_constraint(batch_op.f("ck_research_jobs_running_lease"), type_="check")
        batch_op.drop_column("next_attempt_at")
        batch_op.drop_column("lease_expires_at")
        batch_op.drop_column("claim_token")
        batch_op.drop_column("worker_id")

    # ### end Alembic commands ###
