from enum import StrEnum


class DegreeLevel(StrEnum):
    MASTERS = "MASTERS"
    PHD = "PHD"
    BACHELORS = "BACHELORS"


class ProfessorStatus(StrEnum):
    NEW = "NEW"
    RESEARCHING = "RESEARCHING"
    SHORTLISTED = "SHORTLISTED"
    CONTACTED = "CONTACTED"
    ARCHIVED = "ARCHIVED"


class ContactType(StrEnum):
    EMAIL = "EMAIL"
    UNIVERSITY_PROFILE = "UNIVERSITY_PROFILE"
    LAB_PAGE = "LAB_PAGE"
    ORCID = "ORCID"
    DBLP = "DBLP"
    GOOGLE_SCHOLAR = "GOOGLE_SCHOLAR"
    SEMANTIC_SCHOLAR = "SEMANTIC_SCHOLAR"
    RESEARCHGATE = "RESEARCHGATE"
    LINKEDIN = "LINKEDIN"
    PROFESSIONAL_CONTACT_FORM = "PROFESSIONAL_CONTACT_FORM"
    OTHER = "OTHER"


class SourceType(StrEnum):
    OFFICIAL_UNIVERSITY = "OFFICIAL_UNIVERSITY"
    OFFICIAL_GOVERNMENT = "OFFICIAL_GOVERNMENT"
    OFFICIAL_FACULTY = "OFFICIAL_FACULTY"
    OFFICIAL_LAB = "OFFICIAL_LAB"
    PUBLICATION = "PUBLICATION"
    ACADEMIC_INDEX = "ACADEMIC_INDEX"
    SECONDARY = "SECONDARY"
    OTHER = "OTHER"


class VerificationStatus(StrEnum):
    VERIFIED_OFFICIAL = "VERIFIED_OFFICIAL"
    VERIFIED_PUBLICATION = "VERIFIED_PUBLICATION"
    VERIFIED_SECONDARY = "VERIFIED_SECONDARY"
    UNVERIFIED = "UNVERIFIED"
    CONFLICTING = "CONFLICTING"
    OUTDATED = "OUTDATED"


class StudyPlanStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    ARCHIVED = "ARCHIVED"


class EmailStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    APPROVED = "APPROVED"
    SCHEDULED = "SCHEDULED"
    SENT = "SENT"
    REPLIED = "REPLIED"
    FOLLOW_UP_DUE = "FOLLOW_UP_DUE"
    CLOSED = "CLOSED"
    FAILED = "FAILED"


class JobType(StrEnum):
    GENERAL_CSC_RESEARCH = "GENERAL_CSC_RESEARCH"
    UNIVERSITY_DISCOVERY = "UNIVERSITY_DISCOVERY"
    UNIVERSITY_RESEARCH = "UNIVERSITY_RESEARCH"
    PROGRAM_RESEARCH = "PROGRAM_RESEARCH"
    PROFESSOR_DISCOVERY = "PROFESSOR_DISCOVERY"
    PROFESSOR_RESEARCH = "PROFESSOR_RESEARCH"
    PROFESSOR_PUBLICATION_RESEARCH = "PROFESSOR_PUBLICATION_RESEARCH"
    STUDY_PLAN_GENERATION = "STUDY_PLAN_GENERATION"
    EMAIL_DRAFT = "EMAIL_DRAFT"
    EMAIL_SEND = "EMAIL_SEND"
    INBOX_SYNC = "INBOX_SYNC"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_FOR_REVIEW = "WAITING_FOR_REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class EntityType(StrEnum):
    UNIVERSITY = "UNIVERSITY"
    PROGRAM = "PROGRAM"
    PROFESSOR = "PROFESSOR"
    PROFESSOR_CONTACT = "PROFESSOR_CONTACT"
    SOURCE = "SOURCE"
    PUBLICATION = "PUBLICATION"
    STUDY_PLAN = "STUDY_PLAN"
    EMAIL_RECORD = "EMAIL_RECORD"
    CONTACT_ATTEMPT = "CONTACT_ATTEMPT"
